### ISSUE TITLE
Create data migration for first step of schema transition

### ISSUE THREAD

**Issue by awenocur** [chop-dbhi/varify-data-warehouse#16] opened 2014-08-22 18:14 UTC
Note that this depends on (PR 2)[https://github.com/cbmi/varify-data-warehouse/pull/2].  I'll attach a pull to this soon.

This shall be a reversible data migration to complete the first step of the greater transition to a new schema.

**Comment by naegelyd** [comment] 2014-08-22 19:16
Unless I'm missing something, this appears to be a duplicate of #17. Closing this as duplicate, reopen if this is different.

**Closed as completed by naegelyd** 2014-08-22 19:16 UTC
